# Generated by Django 3.2.6 on 2021-08-26 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='verification_code',
        ),
    ]
