# Generated by Django 3.2.6 on 2021-08-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_admin', '0003_user_is_training_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_assessment_passed',
            field=models.BooleanField(default=False),
        ),
    ]
